# Generated by Django 5.0.6 on 2024-06-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=40)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Systemsetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysname', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='syslogo')),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(default='Nepal', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='bpost',
            name='status',
        ),
    ]
