# Generated by Django 5.0.6 on 2024-06-08 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_category_systemsetting_remove_bpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpost',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.category'),
        ),
    ]
